version: '3'
services:
    msj-zuul:
        container_name: msj-zuul
        image: msj-zuul:prod
        ports:
            - "9003:9003"
        restart: always
        networks:
            - default
            - app_net
networks: 
    app_net:
        external: true