version: '3'
services:
    consul:
        container_name: consul
        image: consul
        ports:
            - "8500:8500"
        restart: always
        networks:
            - default
            - app_net
networks: 
    app_net:
        external: true